### ISSUE TITLE
Error from xpath_util.xml_path_to_path_elem()

### ISSUE THREAD

**Issue by miott** [CiscoTestAutomation/yang#17]
If a namespace is passed in that does not match Cisco or openconfig namespace this traceback happens:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/miott/ysuite/install/yangsuite/venv/lib/python3.7/site-packages/yang/connector/xpath_util.py", line 272, in xml_path_to_path_elem
    if module:
UnboundLocalError: local variable 'module' referenced before assignment
```

**Comment by miott** [comment]
Issue was resolved in cisco-gnmi library.
