### ISSUE TITLE
yang-connector (19.7) or ncclient (0.6.6) fail to create_subscription to NSO 5.2

### ISSUE THREAD

**Issue by marcob73** [CiscoTestAutomation/yang#4]
yang-connector (19.7) or ncclient (0.6.6) generate different XML versus the one generated by netconf-console (which work fine), ie:

NETCONF CONSOLE (CLIENT):

~~~
MBERETTA-M-K1L8:~ mberetta$ netconf-console -u CISCO15 -p Otbu+2019 --host 10.58.230.45 --port 830 -i
netconf> create-subscription ncs-events
<ok xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"/>

netconf> 
~~~

NETCONF CONSOLE (SERVER):
~~~
<nc:rpc message-id="urn:uuid:5854c9a7-5b4f-4d2c-921b-628d0d218533" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ns0:create-subscription xmlns:ns0="urn:ietf:params:xml:ns:netconf:notification:1.0">
    <ns0:stream>ncs-events</ns0:stream>
  </ns0:create-subscription>
</nc:rpc>

6-Nov-2019::16:11:30.378 **< sess:336 write:
<rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:5854c9a7-5b4f-4d2c-921b-628d0d218533" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ok/>
</rpc-reply>
~~~

PYATS (CLIENT):
~~~
>>> svo.create_subscription(stream_name="ncs-events")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gtandi/pyats/lib/python3.6/site-packages/yang/connector/__init__.py", line 410, in execute
    return super().execute(cls, *args, **kwargs)
  File "/Users/gtandi/pyats/lib/python3.6/site-packages/ncclient/manager.py", line 236, in execute
    huge_tree=self._huge_tree).request(*args, **kwds)
  File "/Users/gtandi/pyats/lib/python3.6/site-packages/ncclient/operations/subscribe.py", line 64, in request
    return self._request(node)
  File "/Users/gtandi/pyats/lib/python3.6/site-packages/ncclient/operations/rpc.py", line 349, in _request
    raise self._reply.error
ncclient.operations.rpc.RPCError: {'type': 'protocol', 'tag': 'unknown-element', 'severity': 'error', 'info': '<?xml version="1.0" encoding="UTF-8"?><error-info xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0"><bad-element>stream</bad-element>\n</error-info>\n', 'path': '\n    /rpc/p36:create-subscription\n  ', 'message': None}
>>>
~~~

PYATS (SERVER):
~~~
<nc:rpc message-id="urn:uuid:90297abb-c47d-486b-91fb-e3f6ed632dd9" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
  <ns0:create-subscription xmlns:ns0="urn:ietf:params:xml:ns:netconf:notification:1.0">
    <nc:stream>ncs-events</nc:stream>
  </ns0:create-subscription>
</nc:rpc>
 
6-Nov-2019::11:03:42.743 **< sess:131 write:
<rpc-reply xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:90297abb-c47d-486b-91fb-e3f6ed632dd9" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-element</error-tag>
    <error-severity>error</error-severity>
    <error-path xmlns:p36="urn:ietf:params:xml:ns:netconf:notification:1.0">
    /rpc/p36:create-subscription
  </error-path>
    <error-info>
      <bad-element>stream</bad-element>
    </error-info>
  </rpc-error>
</rpc-reply>
~~~

**Comment by marcob73** [comment]
Same issue tracked by: https://github.com/ncclient/ncclient/pull/350
